### PR TITLE
[JBEAP-15434] [MODULES-339] JAXP redirection fails on 8u161, also in embedded scenarios 

### PR DESCRIPTION
**Pull request by ivassile**
JBEAP (7.1.z): https://issues.jboss.org/browse/JBEAP-15434

In order to backport MODULES-339 the following upstream issues need to be also backported:
* https://issues.jboss.org/browse/MODULES-258 / PR: https://github.com/jboss-modules/jboss-modules/pull/145
* https://issues.jboss.org/browse/MODULES-323 / PR: https://github.com/jboss-modules/jboss-modules/pull/147
* https://issues.jboss.org/browse/MODULES-327 / PR: https://github.com/jboss-modules/jboss-modules/pull/151
* https://issues.jboss.org/browse/MODULES-341 / Commit: https://github.com/jboss-modules/jboss-modules/commit/0193a67eeec83fea857ae6c98b0472957bb6ae68
* https://issues.jboss.org/browse/MODULES-340 / Commit: https://github.com/jboss-modules/jboss-modules/commit/e0d937748225399698e0069ba296147cdc63629e
* https://issues.jboss.org/browse/MODULES-339 / PR: https://github.com/jboss-modules/jboss-modules/pull/171

### CODE REVIEW

**Comment by dmlloyd** [comment]
Test failures look related.  Seems like there's at least one more critical commit missing?

**Comment by bmaxwell** [comment]
I think I found the missing changes, see my PR which is passing: 
https://github.com/jboss-modules/jboss-modules/pull/220

**Comment by wolfc** [comment]
This PR potentially causes https://issues.jboss.org/browse/MODULES-380

**Comment by dmlloyd** [comment]
We'll get an upstream fix soon; then we can backport to this PR.

**Comment by bmaxwell** [comment]
Richard had a look and I was able to confirm with my test app, this PR should be good.  It looks like the test app had an invalid services file which prior to these bug fixes was being silently ignored and falling back to the JBoss version.

**Comment by ropalka** [comment]
Yes, that was the case @bmaxwell  .

**Pull request merged**
