### PR TITLE
[MODULES-146] Add a (possibly) remote repository to local cache fetching...

### PR DESCRIPTION
**Pull request by ALRubinger**
... mechanism for jboss-modules, implemented as a ModuleLoader

### CODE REVIEW

**Comment by ALRubinger** [comment]
Hey @dmlloyd; went to do a rebase and can't build master; got a set of build instructions to point me to?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project jboss-modules: Compilation failure
[ERROR] /home/alr/business/jboss/git/jboss-modules/jboss-modules/src/main/java/org/jboss/modules/ref/package-info.java:[26,1] modifier deprecated not allowed here
```

Environment:

```
$ mvn -verison
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /home/alr/opt/apache/maven/apache-maven-3.3.9
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /home/alr/opt/oracle/java/jdk1.8.0_74/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.7.2-201.fc24.x86_64", arch: "amd64", family: "unix"
```

**Comment by dmlloyd** [comment]
Ah I bet my last commit introduced that. I wonder why the annotation is allowed there then... I'll look at it tomorrow.

**Comment by ALRubinger** [comment]
Thanks!  I might take a couple days after that; long-haul travel but I'll come back to it.  I remember this one being a fun issue.

**Comment by dmlloyd** [comment]
Retest this please

**Pull request closed without merging**
