### PR TITLE
[MODULES-395] Initiallize to AllPermissions the default permission collection for the ModuleSpec builder

### PR DESCRIPTION
**Pull request by yersan**
I'll backport to master if finally the patch is accepted.

Jira Issue: https://issues.jboss.org/browse/MODULES-395

### CODE REVIEW

**Comment by dmlloyd** [comment]
It seems like the CI failures might be related?

**Comment by yersan** [comment]
Looking ...

**Comment by yersan** [comment]
I got the same errors on 1.9 branch, without this patch, so it is unrelated. It looks like a problem downloading the xerces jar file, seems to be empty. I'm looking for the root error. The same test fails with master branch too.

**Comment by dmlloyd** [comment]
I reran the upstream tests and it looks like it's broken there too.  The tests have to be fixed before I can merge anything else though.

**Comment by yersan** [comment]
@dmlloyd Added a second commit to fix the tests. The nexus maven URL was giving us a 302 when the files are being downloaded by http. So, changed the URL to https and add code to follow up links if a 302 is received again.

**Comment by dmlloyd** [comment]
Great, thanks!

**Comment by yersan** [comment]
@dmlloyd I was going to backport the change but I'm not sure about how the branching model for JBoss modules is, do you need to backport the change to the other branches master, 1.x and 2.x?

**Comment by dmlloyd** [comment]
I can merge it into the other branches.  I've been using a strategy of merging the downstream branches into the upstream ones periodically.

Thanks!

**Pull request merged**
