### PR TITLE
[MODULES-453] Add deprecation warnings for Security Manager related command line arguments and skip providers setup on JDK24+

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/MODULES-453

### CODE REVIEW

**Comment by bstansberry** [comment]
I consider writing warning messages to stderr to be a breaking change.

**Review by dmlloyd — CHANGES_REQUESTED** [review]
I don't think this is correct. Security provider registration should still be supported in 24+ IIRC, and is not related to the security manager removal.

**Comment by bstansberry** [comment]
My preference is that deprecating the SM in visible-at-runtime ways (i.e. not @Deprecated) be left to Java SE or to higher level applications like WildFly / EAP. It will be very hard to do anything coherent if libraries are trying to drive end-user behavior.

**Comment by ropalka** [comment]
From my understanding both proposed changes
- added deprecation warning for security related options
-  disabling security provider registrations

are not valid.

**Pull request closed without merging**
