### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Replaces: https://github.com/jboss-modules/jboss-modules/pull/262#pullrequestreview-466118752

**Comment by luck3y** [comment]
@dmlloyd Sorry for the spam. The TARGET thing works great and cleans this up a lot, and I added JDK 9 & 10.

**Comment by luck3y** [comment]
Note, test run here: https://github.com/luck3y/jboss-modules/actions/runs/205933063

**Review by dmlloyd — APPROVED** [review]

**Comment by dmlloyd** [comment]
Thanks!

**Comment by luck3y** [comment]
My pleasure! As before, going to disable the CI triggers for TC. Will keep the jobs around for a while in case they're needed.

**Pull request merged**
