### PR TITLE
[MODULES-378] Module resource loader follows symbolic links (1.8.x)

### PR DESCRIPTION
**Pull request by spyrkob**
1.8 port of #250

JIRA: https://issues.redhat.com/browse/JBEAP-18544

Upstream issue: https://issues.redhat.com/browse/JBEAP-18585 / https://issues.redhat.com/browse/MODULES-378
Upstream PR: #251 / #250

### CODE REVIEW

**Comment by ropalka** [comment]
Why is backport to 1.8 branch needed @spyrkob ?

**Comment by spyrkob** [comment]
@ropalka we need to fix the issue on EAP 7.2.x stream which is using jboss-modules 1.8.8.

**Comment by dmlloyd** [comment]
We need to fix the CI issue before we can merge this PR.  The CI issue is likely due to a mistake in the test which assumes a certain test environment, and it would need one or two backports of fixes from later branches to correct.

**Comment by spyrkob** [comment]
@dmlloyd i think the failures were caused by missing backport of MODULES-395. I opened #253 to fix that

**Pull request merged**
