### PR TITLE
Remove deprecated `ModuleIdentifier` support

### PR DESCRIPTION
**Pull request by dmlloyd**
This class has been deprecated for many years.

### CODE REVIEW

**Comment by ropalka** [comment]
IMO for this change we will need a new main branch and keep 2.x backward compatible with EAP8 @dmlloyd .

**Comment by ropalka** [comment]
Please rebase this PR @dmlloyd

**Review by ropalka — APPROVED** [review]

**Comment by ropalka** [comment]
Overall this PR looks good to me @dmlloyd . I didn't merge it because it is in the draft state.

**Comment by dmlloyd** [comment]
If you think it's okay to merge in the 2.x branch, then I am okay with it being merged.

**Comment by ropalka** [comment]
Thanks @dmlloyd !

**Pull request merged**
