### PR TITLE
Partial revert of commit id: b1a84e9a Move some functions out of JDKSpecific and simplify

### PR DESCRIPTION
**Pull request by ropalka**
I had to create this partial revert because this change introduced a regression in WildFly

Follows up on: https://github.com/jboss-modules/jboss-modules/pull/334

### CODE REVIEW

**Comment by dmlloyd** [comment]
What is the call sequence which fails?

**Comment by ropalka** [comment]
[INFO] --- wfgp:6.5.4.Final:build-feature-pack (feature-pack-build) @ wildfly-core-galleon-pack ---
Forked embedded process has failed with the following error:
java.lang.IllegalStateException: WFLYEMB0022: Cannot invoke 'start' on embedded process
	at org.wildfly.core.embedded.EmbeddedManagedProcessImpl.invokeOnServer(EmbeddedManagedProcessImpl.java:108)
	at org.wildfly.core.embedded.EmbeddedManagedProcessImpl.start(EmbeddedManagedProcessImpl.java:53)
	at org.wildfly.galleon.plugin.featurespec.generator.FeatureSpecGenerator.readFeatureSpecs(FeatureSpecGenerator.java:310)
	at org.wildfly.galleon.plugin.featurespec.generator.FeatureSpecGenerator.forkedForEmbedded(FeatureSpecGenerator.java:235)
	at org.wildfly.galleon.plugin.server.ForkedProcessRunner.main(ForkedProcessRunner.java:56)
Caused by: org.wildfly.core.embedded.EmbeddedProcessStartException: WFLYEMB0021: Cannot start embedded process
	at org.wildfly.embedded@24.0.0.Beta3-SNAPSHOT//org.wildfly.core.embedded.EmbeddedStandaloneServerFactory$StandaloneServerImpl.start(EmbeddedStandaloneServerFactory.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wildfly.core.embedded.EmbeddedManagedProcessImpl.invokeOnServer(EmbeddedManagedProcessImpl.java:96)
	... 4 more
Caused by: java.util.concurrent.ExecutionException: JBTHR00005: Operation failed
	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:253)
	at org.wildfly.embedded@24.0.0.Beta3-SNAPSHOT//org.wildfly.core.embedded.EmbeddedStandaloneServerFactory$StandaloneServerImpl.start(EmbeddedStandaloneServerFactory.java:275)
	... 9 more
Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details. - Server configuration file in use: standalone.xml
	at org.jboss.as.server@24.0.0.Beta3-SNAPSHOT//org.jboss.as.server.ServerService.boot(ServerService.java:427)
	at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:362)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ropalka** [comment]
But I'm trying to debug further - it is the scenario where galleon plugin forks Java processe and I didn't find error logs of this process yet so I'm trying to adjust it somehow to get them.

**Comment by dmlloyd** [comment]
I think I know the problem. It was one I thought carefully about, planned, and then forgot to implement... basically, the caller-sensitivity was changed to be more like how the JDK does it. Each caller-sensitive method uses the immediate caller's class (using the fairly efficient `StackWalker#getCallerClass()` method) always instead of walking the stack to find the first non-`jboss-modules` class. But, the part I forgot to implement was to make sure that no caller-sensitive method is directly invoked from `jboss-modules`. I'll have a fix soon.

**Comment by dmlloyd** [comment]
Could you try #337 to see if it solves the problem?

**Comment by ropalka** [comment]
I finally managed to get the root cause:

java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.wildfly.extension.security.manager
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:99)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1065)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:780)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:470)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1434)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:512)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:452)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:423)
<------>at org.jboss.as.server@24.0.0.Beta3-SNAPSHOT//org.jboss.as.server.ServerService.boot(ServerService.java:455)
<------>at org.jboss.as.server@24.0.0.Beta3-SNAPSHOT//org.jboss.as.server.ServerService.boot(ServerService.java:395)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:362)
<------>at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: WFLYCTL0311: Failed to load Extension module org.wildfly.extension.security.manager
<------>at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
<------>at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:91)
<------>... 11 more
Caused by: java.lang.RuntimeException: WFLYCTL0311: Failed to load Extension module org.wildfly.extension.security.manager
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:137)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:91)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:130)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:111)
<------>at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
<------>at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
<------>at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
<------>at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
<------>at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
<------>at java.base/java.lang.Thread.run(Thread.java:834)
<------>at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: org.jboss.modules.ModuleLoadException: org.wildfly.extension.security.manager
<------>at org.jboss.modules.Module.loadServiceFromCallerModuleLoader(Module.java:454)
<------>at org.jboss.as.controller@24.0.0.Beta3-SNAPSHOT//org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:107)
<------>... 10 more

**Comment by ropalka** [comment]
Going to try your fix proposal @dmlloyd

**Comment by dmlloyd** [comment]
Ah yes, there it is: `at org.jboss.modules.Module.loadServiceFromCallerModuleLoader(Module.java:454)`. The change in #337 should fix this. Thanks!

It might be worth exploring adding some kind of wildfly smoke testing to CI for this project...

**Comment by ropalka** [comment]
The problem is still there when testing https://github.com/jboss-modules/jboss-modules/pull/337

**Comment by dmlloyd** [comment]
Hmm, same exception? That is surprising... is there an easy way to reproduce the problem?

**Comment by ropalka** [comment]
Sure @dmlloyd , please checkout my branches:
[1]  https://github.com/ropalka/jboss-modules/tree/debug
[2] https://github.com/ropalka/wildfly-core/tree/debug
In [1] please update DebugUtils.DEBUG_FILE variable to match your FS
Then:
[3]  `mvn clean install -DskipTests=true` with project [1]
[4] `mvn clean install -DskipTests=true` with project [2]
When WF build will fail for you you'll see the debug file in your DebugUtils.DEBUG_FILE Location.

**Comment by dmlloyd** [comment]
Ah I see. I developed the patch on top of the "remove ModuleIdentifier" patch, and thus missed the methods that use `ModuleIdentifier`. I think maybe I can add some tests or assertions or something...

**Comment by dmlloyd** [comment]
With the new fixes, the failure isn't triggered in the debug build. #337 has been updated ([here is what I changed to make it work](https://github.com/jboss-modules/jboss-modules/compare/79bc1dc1e9633ecdaec3c998b120699a9da80596..a7bb4e69d5808cb6ad147775a4cc7f782cad5694)). Thanks, and sorry for the extra trouble.

**Comment by ropalka** [comment]
No problem @dmlloyd . I'm going to test it ...

**Comment by ropalka** [comment]
Closing in favor of https://github.com/jboss-modules/jboss-modules/pull/337

**Pull request closed without merging**
