### PR TITLE
added support for property expansion in permissions/grant/name attribute

### PR DESCRIPTION
**Pull request by jasinner**
https://issues.jboss.org/browse/MODULES-236

### CODE REVIEW

**Comment by dmlloyd** [comment]
This code was copied without copyright or license headers, and it's not clear what the license or copyright status of this code is.  Furthermore, it's not clear that we are legally authorized to relicense the code as ASL.  If this code came from OpenJDK, we definitely are not, since the license of that code (modified GPL + CDDL) does not allow us to relicense the code as ASL as far as I'm aware.

**Comment by jasinner** [comment]
Can we use org.jboss.dmr.ValueExpressionResolver instead of the JDK code?
If so, can we add a dependency from jboss-modules to org.jboss.dmr, or do you want to keep it pure, and just copy in the ValueExpressionResolver minus the code we don't need?

**Comment by dmlloyd** [comment]
It is impossible to add dependencies from jboss-modules to other projects.  So the code would have to be copied, but then stripped down and probably modified to match all the rules defined in the [Oracle specification] (https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html#PropertyExp).

**Comment by dmlloyd** [comment]
Also the code should be non-public, and I think it should be a part of the XML parsing, not the permission factories themselves.

**Comment by dmlloyd** [comment]
This is ok to test

**Comment by dmlloyd** [comment]
(that's just to satisfy the CI bot)

**Comment by jasinner** [comment]
@dmlloyd Hi David,
I think you are requesting some changes, and I am happy to make changes. However I don't understand what I need to change. Is it possible for you to make the changes yourself?

**Comment by dmlloyd** [comment]
Not at the moment, though I can possibly look into it if/when things calm down.

**Comment by dmlloyd** [comment]
This was replaced by #94.

**Pull request closed without merging**
